### ISSUE TITLE
Newly ignored plugins or display names changed are not respected

### ISSUE THREAD

**Issue by zbranzov** [NativeScript/nsplugins-internal#102]
Recently, we changed the name of nativechat and ignored a duplicate of it but to no result in the marketplace.

https://github.com/NativeScript/marketplace/commit/e23aa82efb72b04efbcdc030ca9d3381e72200ea

**Comment by lini** [comment]
Only updated (new version) plugins are processed when the marketplace database runs a scheduled sync.  If you change the name of the plugin and want to see the changes immediately, start a manual sync with a filter (the name of the plugin) to force an update in the database.
