### ISSUE TITLE
Add privacy policy document in the marketplace

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nsplugins-internal#108]
The document should describe that we are using public user data from NPM and advice the users to update/remove their data from there. We should also refer the nativescript PP document.

**Comment by radeva** [comment]
Menu Item name: Privacy
Title: Customer Data & Privacy
Text:
Plugins, Templates and Samples authors' personal data (npm username, github username, name, email, twitter handle) in NativeScript Marketplace is fetched from [npm](https://www.npmjs.com/) and [GitHub](https://github.com/). In case you would like your data to be changed or erased from this website, please follow the instructions [here](TODO: link to be provided by legal). 

To read more about how Progress Software handles personal data, please review our [privacy policy](https://www.progress.com/legal/privacy-policy).
