### ISSUE TITLE
Samples issues

### ISSUE THREAD

**Issue by DimitarTodorov** [NativeScript/nsplugins-internal#110]
Issues in Samples tab.

- Scrolls are shown on low resolutions over categories and frameworks labels.
https://www.screencast.com/t/RxQ7ZLG7.

- On mobile device(both Android/iOS) and on small resolution on desktop, the 'framework' and 'categories' labels are not positioned well. The font became bigger and they are overlapping. https://www.screencast.com/t/7mXE6BGTyS

- Some samples are not easy to find because there is no 'All' option for frameworks, like the 'All' option in categories.

**Comment by elena-p** [comment]
The marketplace has been redesigned and these issues are not relevant any more
