### ISSUE TITLE
Migrate templates to new structure

### ISSUE THREAD

**Issue by radeva** [NativeScript/nsplugins-internal#116]
Contact Roskata for more details

**Comment by lini** [comment]
https://gist.github.com/rosen-vladimirov/db05391603646ae3b40e13563cc8c4f2#project-creation-v2

**Comment by tgpetrov** [comment]
The following templates are migrated to v.2 (merged in master):
- tns-template-hello-world: [ng](https://github.com/NativeScript/template-hello-world-ng); [ts](https://github.com/NativeScript/template-hello-world-ts); [js](https://github.com/NativeScript/template-hello-world)
- tns-template-drawer-navigation: [ng](https://github.com/NativeScript/template-drawer-navigation-ng); [ts](https://github.com/NativeScript/template-drawer-navigation-ts); [js](https://github.com/NativeScript/template-drawer-navigation)
- tns-template-master-detail: [ng](https://github.com/NativeScript/template-master-detail-ng); [ts](https://github.com/NativeScript/template-master-detail-ts); [js](https://github.com/NativeScript/template-master-detail)
- tns-template-master-detail-kinvey: [ng](https://github.com/NativeScript/template-master-detail-kinvey-ng); [ts](https://github.com/NativeScript/template-master-detail-kinvey-ts); [js](https://github.com/NativeScript/template-master-detail-kinvey)
- tns-template-tab-navigation: [ng](https://github.com/NativeScript/template-tab-navigation-ng); [ts](https://github.com/NativeScript/template-tab-navigation-ts); [js](https://github.com/NativeScript/template-tab-navigation)
- tns-template-blank: [ng](https://github.com/NativeScript/template-blank-ng); [ts](https://github.com/NativeScript/template-blank-ts); [js](https://github.com/NativeScript/template-blank)
- tns-template-patient-care: [ng](https://github.com/NativeScript/template-patient-care-ng)
- tns-template-health-survey: [ng](https://github.com/NativeScript/template-health-survey-ng)

The following templates' migration to v.2 have PRs waiting approval
- tns-template-enterprise-auth: [ng](https://github.com/NativeScript/template-enterprise-auth-ng); [ts](https://github.com/NativeScript/template-enterprise-auth-ts); [js](https://github.com/NativeScript/template-enterprise-auth)
- tns-template-find-a-doctor: [ng](https://github.com/NativeScript/template-find-a-doctor-ng)
