### ISSUE TITLE
Construction Site Inspection - template with mocked data

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nsplugins-internal#119]
https://xd.adobe.com/view/7e0317c6-3425-403f-75d5-123072fc3af3-0832/

Update the template with UX (remove all images)

child of #114

**Comment by tbozhikov** [comment]
Acceptance criteria:
- The new app should be able to be built using the template https://github.com/NativeScript/template-construction-sites
- Offline support (CRUD of items should persist to Kinvey cloud once the app becomes online) 
- At least one image should be able to be stored per site. Several images per site are optional
