### ISSUE TITLE
Migrate plugins & demos for N4.2

### ISSUE THREAD

**Issue by nsplugins** [NativeScript/nsplugins-internal#124]

**Comment by lini** [comment]
P1:
- [ ] Publish https://github.com/NativeScript/template-enterprise-auth
- [ ] Publish https://github.com/NativeScript/template-enterprise-auth-ng
- [ ] Publish https://github.com/NativeScript/template-enterprise-auth-ts
- [ ] Publish https://github.com/NativeScript/template-patient-care-ng
- [ ] Publish https://github.com/NativeScript/template-health-survey-ng

P2:
- [ ] update plugin demo apps
- [ ] update plugin dependencies
