### ISSUE TITLE
Update and automate the PRO UI samples

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nsplugins-internal#126]
- split the big examples into multiples demos
- update the demos with the latest code from the private repos
- update the links in the pro ui docs
- automate the migration using a jenkins job

**Comment by DimitarTodorov** [comment]
AC:
 - All split demo apps should build with webpack and in release
 - Documentation should be updated:
   - update the links in the pro ui docs 
 - Jenkins build for changes sync should be available
 - On jenkins build - PR should be created in the public repo with relevant changes
