### ISSUE TITLE
Remove webpack dependencies

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nsplugins-internal#127]
we should update the demos of all plugins and templates:

check here: https://github.com/NativeScript/nativescript-dev-webpack/issues/569 (ping Mira for more details)

**Comment by lini** [comment]
https://github.com/NativeScript/template-enterprise-auth/pull/16
https://github.com/NativeScript/template-enterprise-auth-ts/pull/19
https://github.com/NativeScript/template-enterprise-auth-ng/pull/33

**Comment by lini** [comment]
https://github.com/NativeScript/nsplugins-internal/issues/127
