### ISSUE TITLE
Dataform css issues

### ISSUE THREAD

**Issue by zbranzov** [NativeScript/nsplugins-internal#152]
- https://screencast.com/t/JfqQqNkf If you increase the width of the border it will shrink editors width.
- https://screencast.com/t/1cgnKPqn  color is not applied to Date and Time but it is on Picker
- https://screencast.com/t/QPm98exej  RadDataForm DataFormEditorCore width and height don't apply on iOS
- https://screencast.com/t/imxyAykdsj If you remove the 'position' property in RadDataForm DataFormEditorLabel it will reset width of the label in android and put it on top of the editor maybe because of the new width value. 
- https://screencast.com/t/pDifcUlU setting 'position' to 'right' | "top" resets width of label and puts it on top
- when RadDataForm is inside StackLayout it is not measuring correctly when it has padding (the padding is not included in the size causing the form to become scrolling even though there is enough space to stretch it fully)

**Comment by tgpetrov** [comment]
The 3rd issue (RadDataForm DataFormEditorCore width and height don't apply on iOS) is expected. Currently `width` and `height` are not supported for DataFormEditorCore. I have listed all we currently support in [this](https://github.com/telerik/nativescript-ui-docs/blob/master/Controls/NativeScript/DataForm/dataform-styling.md#css) docs article. There are also other properties that are not supported (like text-align, text-decoration, placeholder-color, etc.). Let's start with the current set and gradually expand it in accordance with the demand.
