### ISSUE TITLE
Chart Test Vue support latest changes

### ISSUE THREAD

**Issue by zbranzov** [NativeScript/nsplugins-internal#153]
Latest vue changes cause vue app to crash. We have to wait for Manuel to take a look and resolve the issues to be able to produce new releases.

**Comment by VladimirAmiorkov** [comment]
Related to https://github.com/telerik/nativescript-ui-feedback/issues/866

**Comment by zbranzov** [comment]
awaits https://github.com/NativeScript/nsplugins-internal/issues/154
