### ISSUE TITLE
[Android] Demo for autocomplete crash on navigate back, after resuming the app

### ISSUE THREAD

**Issue by DimitarTodorov** [NativeScript/nsplugins-internal#167]
When suspend the demo app and resume it, navigating back throws an exception and makes the app to crash.

Steps to reproduce: 
1. Open the app on Android device
2. Navigate to some example( e.g. getting started)
3. Suspend the app
4. Resume the app and navigate back from action bar

Actual: The app crashes
Expected: The app should navigate back

**Comment by elena-p** [comment]
Copied in https://github.com/telerik/nativescript-ui-feedback/issues/1037
