### ISSUE TITLE
Do not use type string for enumerations

### ISSUE THREAD

**Issue by tgpetrov** [NativeScript/nsplugins-internal#169]
Currently there are a lot of properties that look like enumerations but are of type string. For example Chart's [pointSelectionMode](https://github.com/NativeScript/nativescript-ui-chart/blob/master/src/index.d.ts#L128), Calendar's [viewMode](https://github.com/NativeScript/nativescript-ui-calendar/blob/master/src/index.d.ts#L1224), DataForm's [commitMode](https://github.com/NativeScript/nativescript-ui-dataform/blob/master/src/index.d.ts#L128), etc. We should change them to enumerations and release major versions of the related plugins.

- [x] AutoComplete - Released
- [x] Calendar - Released
- [x] Chart - Released
- [x] DataForm - needs an AutoComplete release first
- [x] Gauge - Released
- [x] ListView - released
- [x] SideDrawer - Released

**Comment by DimitarTodorov** [comment]
AC:
- [ ] Properties should be applied when set from both xml and code behind - with Enum values.
- [ ] Available enum values should be described in a documentation
