### ISSUE TITLE
Release a version compatible with AndroidX for our plugins

### ISSUE THREAD

**Issue by tgpetrov** [NativeScript/nsplugins-internal#184]
For all plugins from [this list](https://docs.google.com/spreadsheets/d/1AWlWG3MohvrmbmjrTUO0Mwu-vTIsPy9BNAMHXZrR5Jk/edit#gid=1141407148) with author {N} Team, which have a check for "Should migrate" we should prepare a version compatible with AndroidX. If this version is also compatible with the old Support Libraries we should make an official release, otherwise the new version should be published with androidx tag.

**Comment by DimitarTodorov** [comment]
AC: 
- [ ] All plugins should have androidX branches with updated dependencies
- [ ] PR checks must pass before releasing androidX tag in npm
- [ ] AndroidX tag should be published in npm

**Comment by tgpetrov** [comment]
Here are the compatible versions released:

nativescript-ui-core - androidx
nativescript-ui-autocomplete - androidx
nativescript-ui-calendar - androidx
nativescript-ui-chart - androidx
nativescript-ui-dataform - androidx
nativescript-ui-gauge - androidx
nativescript-ui-listview - androidx
nativescript-ui-sidedrawer - androidx

nativescript-imagepicker - 6.2.0
nativescript-geolocation - 5.1.0
nativescript-camera - 1.5.0
nativescript-datetimepicker - 1.1.0
nativescript-background-http - no need to migrate
nativescript-facebook - no need to migrate
nativescript-brightness - no need to migrate
nativescript-picker - no need to migrate
