### ISSUE TITLE
AutoComplete CSS Support

### ISSUE THREAD

**Issue by tgpetrov** [NativeScript/nsplugins-internal#193]

**Comment by tgpetrov** [comment]
AC:
1. These selectors should be covered with examples:
**RadAutoCompleteTextView**
color
background
padding
margin
border (width, color, radius)
font (size, weight)
enums (display-mode, completion-mode, etc.)

**RadAutoCompleteTextView:focus**

**ClearButton**
color 
background-image

**SuggestionView**
color
background
margin
border (width, color, radius)
font (size, weight)

**Token**
color
background
padding
margin
border (width, color, radius)
font (size, weight)

**Token:selected**

**TokenClearButton**
color
background-image

2. Add e2e tests for the examples
3. Styles should be applied correctly on android and on iOS
4. Styles applied from xml/html as well

**Comment by DimitarTodorov** [comment]
Issues: 

- [ ] [Android]When type in autocomplete and delete the value, the suggestion left, when autocomplete is in Append mode.

**Comment by DimitarTodorov** [comment]
Published with 5.1.0 of nativescript-ui-atocomplete.
