### ISSUE TITLE
TP related tasks

### ISSUE THREAD

**Issue by radeva** [NativeScript/nsplugins-internal#30]
- Export buttons
- Create App mesages
- Top message
- Documentation (sync with Garo and Evgeni)

**Comment by zbranzov** [comment]
Notes:
- The Export button does not export. Maybe it would be nice if we change button color as we do for all clickable elements on hover.
- Migration guide link seems strangely wrapped and leads nowhere.
- Learn More button leads nowhere
- On Create App > Advanced - we should change warning depending on the template's type (Hybrid | NativeScript)
- NS warning 'Try now' button does nothing.

**Comment by zbranzov** [comment]
- Typo https://screencast.com/t/67LFofe5talg
- On export we don't use app latest name if changed https://screencast.com/t/iOokmyOMdO7 . This seems to be existing issue on livе тоо so we can drop it.
