### ISSUE TITLE
Align across repos: License & Code of Conduct

### ISSUE THREAD

**Issue by radeva** [NativeScript/nsplugins-internal#50]
- Align license and Code of Conduct
   ? link the code of conduct repo from all {N} repos OR include it in all repos
   ? review all License files and update where needed
- Get the list of repos from https://progresssoftware.sharepoint.com/:w:/r/sites/NativeScript/_layouts/15/Doc.aspx?sourcedoc=%7B20604FC5-0873-41BA-890A-561F113C0FA5%7D&file=OSS%20good%20practices%20research.docx&action=edit&mobileredirect=true&DefaultItemOpen=1
- Automate the process of propagating changes to the content of these files.

**Comment by tbozhikov** [comment]
Acceptance Critera:
- all repos from the list should have LICENSE file - Apache 2.0
- all repos from the list should appear in Github as licensed under Apache 2.0
- all repos from the list should have CODE_OF_CONDUCT.md file

**Comment by tbozhikov** [comment]
We executed the tool for the repos in this file:
https://github.com/NativeScript/github-repos-updater/blob/master/config.json
... and the following 2 repos 
    https://github.com/NativeScript/playground-tests.git/   
    https://github.com/NativeScript/starter-kit-tests.git/
failed with error: 
git push --set-upstream origin tbozhikov/update-license -> remote: Repository not found.

??? should we apply these changes for:
https://github.com/NativeScript/nativescript-cloud
