### ISSUE TITLE
Documentation for data operations for RadListView

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nsplugins-internal#73]

**Comment by VladimirAmiorkov** [comment]
Vanila {N} article here: http://testdocs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/data-operations

Angualr {N} aritcle here: http://testdocs.telerik.com/devtools/nativescript-ui/Controls/Angular/ListView/data-operations

**Comment by DimitarTodorov** [comment]
- The link in the angular documentation points to the sdk example, instead to sdkAngular example.

**Comment by VladimirAmiorkov** [comment]
@DimitarTodorov Thanks, I will fix it now.
