### ISSUE TITLE
[Research] Pro UI ListView vs Core ListView

### ISSUE THREAD

**Issue by radeva** [NativeScript/nsplugins-internal#79]

**Comment by nsplugins** [comment]
Research results https://progresssoftware.sharepoint.com/:x:/r/sites/NativeScript/_layouts/15/WopiFrame.aspx?sourcedoc={9adda5ef-f457-4412-868d-9519757186b5}&action=edit&activeCell=%27Sheet1%27!C56&wdInitialSession=7c178c4f-9fe2-4494-ad46-f0826d6ec6a2&wdRldC=1
