### ISSUE TITLE
[Research] Push vs Firebase

### ISSUE THREAD

**Issue by radeva** [NativeScript/nsplugins-internal#80]
- Research: Push vs Firebase
- Triage issues
- Remove hooks if needed
- (based on research) Add dependency to Firebase plugin and option in iOS to choose which Push Notifications approach to use OR consider replacing push plugin with Firebase

**Comment by tbozhikov** [comment]
NOTES after research:
https://wiki.progress.com/pages/viewpage.action?pageId=253505469
