### ISSUE TITLE
Polish pro ui repos dev workflow

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nsplugins-internal#83]
1) fix native d.ts files (currently the demos using native d.ts files are getting tsc errors)
2) remove submodules
3) add the native builds in the src build script
4) add the `xcpretty` issue in the readme
5) follow OSS practices and add all missing files like contribution.md
6) add a watch command for transpiling the ts + rebuilding the native code
7) move the native code to a submodule

**Comment by tgpetrov** [comment]
1.	Here’s how the d.ts are now organised:
a.	src/android.d.ts -> references from src/platforms/android/typings/*.d.ts
b.	src/ios.d.ts -> references from src/platforms/ios/typings/*.d.ts
c.	src/references.d.ts -> references files from src/*.d.ts
d.	demo/references.d.ts -> references relative paths from src directory
2.	The native projects now reference core from src/node-modules/nativescript-ui-core
3.	There are now build.android, build.ios and build.native npm scripts to build the native code
4.	The xcpretty is removed from the ios build so it is no longer required
5.	Contributing, DevelopmentWorkflow and pull_request_template files have been added
6.	A command plugin.watch has been added
7.	Cancelled
8.	Errors are resolved

**Comment by tgpetrov** [comment]
AC:
1. Running `npm run tslint` has no errors.
2. All demos are working
3. Verify documentation steps
