### ISSUE TITLE
Pressing the "physical" back button exits the app directly on Android with RadSideDrawer as root element

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nsplugins-internal#84]

**Comment by VladimirAmiorkov** [comment]
This can be tested in branch amiorkov/as-root: https://github.com/NativeScript/nativescript-ui-sidedrawer/tree/amiorkov/as-root

**Comment by zbranzov** [comment]
AC:
- After navigation in the app you should be able to get back using the hardware back button of the device
- on root level, back button should close the app

**Comment by igorjacauna** [comment]
I have same problem. If child frame navigate, if press back button the application exit instead back to previous page in child frame
