### ISSUE TITLE
HT#3: Out of pocket calculator

### ISSUE THREAD

**Issue by radeva** [NativeScript/nsplugins-internal#93]
Check https://github.com/NativeScript/template-find-a-doctor-ng/issues/13 for details.

**Comment by tbozhikov** [comment]
A preliminary draft of mini-tasks for this job (+ rough estimates): 
- [4] integrate TabView into template
    - Find doctor functionality should work as previously, only calculator tab should be empty
    - Plan information should show OK
- [1] communicate with Kinvey Team (Ivo, Jikku) on common backend
- [1] communicate with UX team (Tyanko) on UX
- OOP calculator tab
    - [1] implement List with search (service for getting all medical procedures, search filter ???) 
    - [4] implement Result screen with info button, Outpatient and Inpatient bars, and breakdowns
    - [1] implement Info modal page accessible from Result screen 

Out-of-Pocket Calculator architecture:
https://docs.google.com/document/d/1eXERmU2C1K2ei_sXnHlKpuNoPD9LVF2Pi6owuRkmZgM/edit#

**Comment by tbozhikov** [comment]
Acceptance criteria:
- tabview with 3 tabs (OOP calc in the middle). The icons should highlight properly  when selected and should be sized proportionally
- search in listview should filter as you type
- consent check should be present with default value false before submitting the search
- result screen should show correct price range from the shown facilites estimates

**Comment by zbranzov** [comment]
ANDROID issues:
- Unable to tap last item in the search doctor https://screencast.com/t/Yacqpetsh6
- Once the keyboard pops up it makes search textfield impossible to edit. You cannot use your fingers to insert something. You can only delete or input in sequence. https://screencast.com/t/5vDezx4KIP
- Find result page says nothing - https://screencast.com/t/bK8eFfgTQIk
- No log out option
- Search in OOP tab has the same issues as on iOS
- Loading the app show default NS logo https://screencast.com/t/nAGLyh7DQ
