### ISSUE TITLE
Header animation

### ISSUE THREAD

**Issue by radeva** [NativeScript/nsplugins-internal#97]

**Comment by tgpetrov** [comment]
AC:
1. Transitions should be as in the design
2. When moving from list page to detail page:
- animation of the image from its position to the top
- animation of the content from the bottom to the top
- menu button in action bar changes to back arrow
- search button disappears
3. When scrolling:
- image height changes
- image scale increases
4. Should behave the same way on iOS and Android
5. The sample is on the playground and should be always available (make sure it's not deleted)

**Comment by tgpetrov** [comment]
The animation is here:
https://play.nativescript.org/?template=play-ng&id=iDY4kF
